### ISSUE TITLE
"Quick Edit" turns off autopost

### ISSUE THREAD

**Issue by edent** [janboddez/share-on-mastodon#29]
Love the plugin. Small glitch with scheduled posts.

1. Create a new post
1. Schedule the post for a future date
1. On the Scheduled Posts page, click "Quick Edit"
1. Change the date to later
1. Click save

The post will not auto-share to Mastodon.

Happy to provide more details if necessary.

**Comment by janboddez** [comment]
Interesting. I never actually tried it with scheduled posts. :-S

Do you happen to know if the `_share_on_mastodon` meta field gets set when the post is first saved/scheduled? (It should be `'1'`, at least if the meta box checkbox was checked.) Because the "Quick Edit" function should leave that one untouched (unless it doesn't, somehow).

**Comment by janboddez** [comment]
Perfect!

Yeah, so it won't syndicate the post if the meta field isn't there (unless you use the `share_on_mastodon_enabled`, I think it was, filter, which is the probably way to go when posting from, e.g., a mobile app---another solution would be to set the custom field through another hook/callback).
