### ISSUE TITLE
Provide status on post to Mastodon

### ISSUE THREAD

**Issue by davehill47** [janboddez/share-on-mastodon#44]
Would it be possible to (optionally) add a status message on the WP post edit screen when a successful share is made? This would present similarly to the existing "Post published and sending emails to subscribers. View post" or "Post updated. View post" messages, in its own status box. (WP-to-Twitter, when I was using that, did something similar.) So, something like ... 

> Shared to Mastodon at ____________

... filling in the location site (as the meta box does).

This would provide positive confirmation the share worked or occured, without having to scroll to where the meta box is.

**Comment by janboddez** [comment]
Is that using Gutenberg?

I mean, I think so, because on "Classic Editor" screens, I normally just drag the meta box up until it sits just below the "Publish" "box thingy."

I've yet to look into these "Post" panels for Gutenberg, hoping to eventually do something with them.

**Comment by davehill47** [comment]
Actually, it's for Classic Editor. And, yeah, if I pull the metabox up, it's just visible. Unfortunately, that means pulling something else further down out of sight. :-)  But that is a workaround, so from my perspective this is low priority.

**Comment by janboddez** [comment]
Hehe. I never know if I want the featured image to be (barely) visible (above the fold), or this plugin's metabox or maybe "Share on Pixelfed's," and so on.

> Unfortunately, that means pulling something else further down out of sight.

Yeah, we could maybe show a dismissible notice or something, although for _delayed_ syndication it would obviously never be displayed.

I'll look into it, but, yeah, rather low prio. (The Gutenberg case is worse, because there the meta box doesn't auto-update upon publish [but we could, eventually, possibly show a post-publish "sidebar message"].)

**Comment by janboddez** [comment]
I actually added this, **but** it is off by default.

You'd have to add `add_filter( 'share_on_mastodon_admin_notices', '__return_true' );` to your theme's `functions.php`, or, better still, a must-use plugin.

**Comment by janboddez** [comment]
Was shipped in v0.10.0.

**Comment by davehill47** [comment]
Works like a champ -- thanks!
