### ISSUE TITLE
No reactivation after upgrade

### ISSUE THREAD

**Issue by toncijajic** [janboddez/share-on-mastodon#47]
On one of our partner's sites, the plugin auto-updated on 2022-12-20 and failed to reactivate after installation.

No PHP errors pertaining to the plugin were logged at that time.

Before the fact, the plugin was working as expected.

Let me know if I could help with more details.

**Comment by janboddez** [comment]
Oh, that's a first.

Typically, when a plugin is deactivated like that, its path changed. Plugins, as far as I'm aware, don't normally deactivate themselves—I mean, it's extremely unlikely that this was caused by a bug in the code itself.

Maybe the plugin had been installed from GitHub, in a folder called `share-on-mastodon-master`? And, after updating, got (re-)installed into `share-on-mastodon`? That'd be the most likely explanation that I can think of ... (Other than a very rare glitch of WP itself?)

**Comment by toncijajic** [comment]
@janboddez thanks for the reply!

> Maybe the plugin had been installed from GitHub, in a folder called share-on-mastodon-master? And, after updating, got (re-)installed into share-on-mastodon? That'd be the most likely explanation that I can think of ..

This actually might be the case. I'll dig through out documentation for the site to see if we added the plugin via WPORG or GitHub, and post back here.

**Comment by toncijajic** [comment]
Hey @janboddez, I can confirm ti was indeed this:

> Maybe the plugin had been installed from GitHub, in a folder called share-on-mastodon-master? And, after updating, got (re-)installed into share-on-mastodon? That'd be the most likely explanation that I can think of ... (Other than a very rare glitch of WP itself?)

Closing this, thanks so much for the help!
